services:
  - type: web
    name: vync-backend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://vync-omega.vercel.app
      - key: VITE_SOCKET_URL
        value: https://vync-d54m.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: REDIS_URL
        sync: false